packages:
  - ".pkgs/*"
  - "apps/*"
  - "packages/*"
  - "packages/*/*"
  - "examples/*"
onlyBuiltDependencies:
  - core-js
  - dprint
  - esbuild
  - sharp
overrides:
  "@eslint/js": "9.39.2"
  "@types/react": "^19.2.14"
  "@types/react-dom": "^19.2.3"
  "esbuild": "^0.27.3"
  "eslint": "9.39.2"
  "lodash": "^4.17.23"
  "minimatch": "^10.2.1" # https://github.com/Rel1cx/eslint-react/security/dependabot/64
  "next": "^16.1.6"
  "react": "^19.2.4"
  "react-dom": "^19.2.4"
  "ts-api-utils": "^2.4.0"
  "tslib": "^2.8.1"
  "typescript": "^5.9.3"
  "undici": "^7.22.0"
