packages:
  - .pkgs/*
  - apps/*
  - packages/*
  - packages/*/*
  - examples/*

onlyBuiltDependencies:
  - "@parcel/watcher"
  - core-js
  - dprint
  - esbuild
  - msgpackr-extract
  - sharp

overrides:
  "@types/react": ^19.2.14
  "@types/react-dom": ^19.2.3
  "@typescript-eslint/scope-manager": "canary"
  "@typescript-eslint/type-utils": "canary"
  "@typescript-eslint/types": "canary"
  "@typescript-eslint/utils": "canary"
  esbuild: ^0.27.3
  lodash: ^4.17.23
  minimatch: ^10.2.4
  next: ^16.1.6
  react-dom: ^19.2.4
  react: ^19.2.4
  semver: "^7.7.4"
  ts-api-utils: ^2.4.0
  tslib: ^2.8.1
  typescript-eslint: "canary"
  typescript: ^5.9.3
  undici-types: ^7.22.0
  undici: ^7.22.0

trustPolicy: "no-downgrade"
