packages:
  - .pkgs/*
  - apps/*
  - packages/*
  - plugins/*
  - examples/*

allowBuilds:
  "@parcel/watcher": true
  dprint: true
  esbuild: true
  msgpackr-extract: true
  nx: true
  sharp: true

onlyBuiltDependencies:
  - "@parcel/watcher"
  - core-js
  - dprint
  - esbuild
  - msgpackr-extract
  - sharp

overrides:
  "@types/react": ^19.2.14
  "@types/react-dom": ^19.2.3
  "@typescript-eslint/project-service": "^8.59.3"
  "@typescript-eslint/scope-manager": "^8.59.3"
  "@typescript-eslint/tsconfig-utils": "^8.59.3"
  "@typescript-eslint/type-utils": "^8.59.3"
  "@typescript-eslint/types": "^8.59.3"
  "@typescript-eslint/typescript-estree": "^8.59.3"
  "@typescript-eslint/utils": "^8.59.3"
  "@typescript-eslint/visitor-keys": "^8.59.3"
  axios: ^1.16.1 # Transitive dependency axios 1.15.0 is introduced via nx 22.7.1
  chokidar: ^5.0.0
  defu: ^6.1.7
  dompurify: ^3.4.3
  esbuild: ^0.28.0
  follow-redirects: ^1.16.0
  lodash-es: ^4.18.1
  lodash: ^4.18.1
  mermaid: "^11.15.0"
  minimatch: ^10.2.5
  next: ^16.2.6
  path-to-regexp: "^8.4.2"
  postcss: ^8.5.14
  react-dom: ^19.2.6
  react: ^19.2.6
  semver: "^7.8.0"
  ts-api-utils: ^2.5.0
  tslib: ^2.8.1
  typescript-eslint: "^8.59.3"
  typescript: "^6.0.3"
  undici-types: ^8.2.0
  undici: ^8.2.0
  uuid: ^14.0.0

trustPolicy: "no-downgrade"
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - fumadocs-core
  - fumadocs-docgen
  - fumadocs-mdx
  - fumadocs-twoslash
  - fumadocs-typescript
  - fumadocs-ui
  - import-integrity-lint
