// Rule name primitive definition

type No = "no";

export type PositiveModifier = "enforce" | "prefer" | "require" | "strict" | "use";

export type NegativeModifier = "prevent" | No;

export type Modifier = NegativeModifier | PositiveModifier;

export type NegativeDescriptive =
    | "complicated"
    | "confusing"
    | "danger"
    | "deprecated"
    | "duplicate"
    | "falsely"
    | "forbidden"
    | "incompatible"
    | "inlined"
    | "invalid"
    | "leaked"
    | "legacy"
    | "misleading"
    | "missing"
    | "misused"
    | "mixing"
    | "outdated"
    | "redundant"
    | "restricted"
    | "suppressing"
    | "suspicious"
    | "unescaped"
    | "uninitialized"
    | "unknown"
    | "unreachable"
    | "unsafe"
    | "unstable"
    | "unused"
    | "unwanted"
    | "useless";

export type PositiveDescriptive = "explicit" | "optimal" | "optimized" | "standard" | "strict";

export type NeutralDescriptive =
    | "access"
    | "calling"
    | "constructed"
    | "empty"
    | "extra"
    | "implicit"
    | "inside"
    | "outside"
    | "shorthand";

export type Descriptive = NegativeDescriptive | NeutralDescriptive | PositiveDescriptive;

// Comment out unused terms to reduce the type checking overhead
export type Term =
    // | "any"
    // | "api"
    // | "argument"
    // | "array"
    // | "arrow-function"
    // | "async"
    // | "async-arrow-function"
    // | "async-function"
    // | "async-generator"
    // | "async-iterable"
    // | "attribute"
    // | "await"
    // | "block"
    // | "boolean"
    // | "callback"
    // | "case"
    // | "catch"
    | "array-index"
    // | "class"
    | "cache"
    // | "class-method"
    // | "class-property"
    | "children"
    | "class-component"
    | "clone-element"
    | "comment"
    | "component"
    // | "computed"
    // | "computed-property"
    // | "const"
    // | "constant"
    // | "constructor"
    | "context"
    | "context-consumer"
    | "context-provider"
    | "context-value"
    // | "default"
    // | "default-export"
    | "createRef"
    | "default-props"
    | "deps"
    | "destructuring"
    | "destructuring-assignment"
    | "direct-mutation"
    | "entities"
    // | "dictionary"
    // | "directive"
    // | "display-name"
    // | "document"
    // | "effect"
    // | "element"
    | "event-handler"
    // | "error"
    // | "event"
    | "exhaustive-deps"
    // | "export"
    // | "expression"
    // | "extends"
    // | "external"
    // | "false"
    | "filename"
    | "forward-ref"
    | "function-component"
    // | "function"
    // | "function-name"
    | "handler"
    // | "generator"
    // | "generic"
    // | "getter"
    // | "global"
    | "jsx"
    // | "hook"
    // | "html"
    // | "id"
    // | "index"
    // | "index-signature"
    // | "inferred"
    // | "inferred-type"
    // | "input"
    // | "instance"
    // | "interface"
    | "jsx-attribute"
    | "jsx-boolean"
    | "jsx-conditional-rendering"
    | "jsx-element"
    | "jsx-expression"
    | "jsx-filename"
    | "jsx-fragment"
    | "jsx-handler"
    | "jsx-key"
    | "memo"
    | "memoized-function"
    | "method"
    // | "key"
    // | "keyword"
    // | "label"
    // | "length"
    // | "let"
    // | "literal"
    // | "local"
    // | "loop"
    // | "map"
    // | "member"
    | "ref"
    | "shorthand"
    // | "method"
    // | "module"
    // | "name"
    // | "namespace"
    // | "native"
    // | "nested-components"
    // | "new"
    // | "node"
    // | "null"
    // | "number"
    // | "object"
    // | "override"
    // | "parameter"
    // | "private"
    // | "promise"
    // | "prop"
    // | "protected"
    // | "public"
    // | "pure"
    // | "pure-function"
    // | "query"
    // | "react"
    // | "readonly"
    | "state"
    // | "regexp"
    // | "render"
    // | "return"
    // | "set"
    // | "setter"
    | "string-refs"
    // | "source"
    // | "spread"
    // | "state"
    // | "static"
    // | "string"
    | "textnodes";
// | "style"
// | "symbol"
// | "tag"
// | "ternary"
// | "type"
// | "undefined"
// | "use-callback"
// | "use-context"
// | "use-effect"
// | "use-imperative-handle"
// | "use-layout-effect"
// | "use-memo"
// | "use-reducer"
// | "use-ref"
// | "use-state"
// | "value"
// | "var"
// | "variable"
// | "void"
// | "weakmap"
// | "weakref"
// | "weakset"
// | "while"
// | "yield"

export type Additional = string;

export type RuleName =
    | `${NegativeModifier}-${NegativeDescriptive | NeutralDescriptive}-${Term}`
    | `${NegativeModifier}-${NegativeDescriptive | NeutralDescriptive}-${Term}-${Additional}`
    | `${No}-${Term}`
    | `${No}-${Term}-${Term}`
    | `${No}-${Term}-${Term}-${Additional}`
    | `${PositiveModifier}-${NeutralDescriptive | PositiveDescriptive}-${Term}`
    | `${PositiveModifier}-${NeutralDescriptive | PositiveDescriptive}-${Term}-${Additional}`
    | `${PositiveModifier}-${Term}`
    | `${PositiveModifier}-${Term}-${Additional}`;
