export default {
  overview: {
    title: "Overview",
    theme: {
      layout: "full",
    },
  },
  "---": {
    type: "separator",
  },
  "avoid-shorthand-boolean": "avoid-shorthand-boolean",
  "avoid-shorthand-fragment": "avoid-shorthand-fragment",
  "ensure-forward-ref-using-ref": "ensure-forward-ref-using-ref",
  "no-access-state-in-setstate": "no-access-state-in-setstate",
  "no-array-index-key": "no-array-index-key",
  "no-children-count": "no-children-count",
  "no-children-for-each": "no-children-for-each",
  "no-children-map": "no-children-map",
  "no-children-only": "no-children-only",
  "no-children-prop": "no-children-prop",
  "no-children-to-array": "no-children-to-array",
  "no-class-component": "no-class-component",
  "no-clone-element": "no-clone-element",
  "no-comment-textnodes": "no-comment-textnodes",
  "no-complicated-conditional-rendering": {
    title: "no-complicated-conditional-rendering",
    // This rule has been deprecated
    display: "hidden",
  },
  "no-component-will-mount": "no-component-will-mount",
  "no-component-will-receive-props": "no-component-will-receive-props",
  "no-component-will-update": "no-component-will-update",
  "no-create-ref": "no-create-ref",
  "no-direct-mutation-state": "no-direct-mutation-state",
  "no-duplicate-key": "no-duplicate-key",
  "no-implicit-key": {
    title: "no-implicit-key",
    // This rule has been deprecated
    display: "hidden",
  },
  "no-leaked-conditional-rendering": "no-leaked-conditional-rendering",
  "no-missing-component-display-name": "no-missing-component-display-name",
  "no-missing-key": "no-missing-key",
  "no-nested-components": "no-nested-components",
  "no-redundant-should-component-update": "no-redundant-should-component-update",
  "no-set-state-in-component-did-mount": "no-set-state-in-component-did-mount",
  "no-set-state-in-component-did-update": "no-set-state-in-component-did-update",
  "no-set-state-in-component-will-update": "no-set-state-in-component-will-update",
  "no-string-refs": "no-string-refs",
  "no-unsafe-component-will-mount": "no-unsafe-component-will-mount",
  "no-unsafe-component-will-receive-props": "no-unsafe-component-will-receive-props",
  "no-unsafe-component-will-update": "no-unsafe-component-will-update",
  "no-unstable-context-value": "no-unstable-context-value",
  "no-unstable-default-props": "no-unstable-default-props",
  "no-unused-class-component-members": "no-unused-class-component-members",
  "no-unused-state": "no-unused-state",
  "no-useless-fragment": "no-useless-fragment",
  "prefer-destructuring-assignment": "prefer-destructuring-assignment",
  "prefer-read-only-props": "prefer-read-only-props",
  "prefer-shorthand-boolean": "prefer-shorthand-boolean",
  "prefer-shorthand-fragment": "prefer-shorthand-fragment",
  "dom-no-children-in-void-dom-elements": "dom/no-children-in-void-dom-elements",
  "dom-no-dangerously-set-innerhtml": "dom/no-dangerously-set-innerhtml",
  "dom-no-dangerously-set-innerhtml-with-children": "dom/no-dangerously-set-innerhtml-with-children",
  "dom-no-find-dom-node": "dom/no-find-dom-node",
  "dom-no-missing-button-type": "dom/no-missing-button-type",
  "dom-no-missing-iframe-sandbox": "dom/no-missing-iframe-sandbox",
  "dom-no-namespace": "dom/no-namespace",
  "dom-no-render-return-value": "dom/no-render-return-value",
  "dom-no-script-url": "dom/no-script-url",
  "dom-no-unsafe-iframe-sandbox": "dom/no-unsafe-iframe-sandbox",
  "dom-no-unsafe-target-blank": "dom/no-unsafe-target-blank",
  "hooks-extra-ensure-custom-hooks-using-other-hooks": "hooks-extra/ensure-custom-hooks-using-other-hooks",
  "hooks-extra-ensure-use-callback-has-non-empty-deps": "hooks-extra/ensure-use-callback-has-non-empty-deps",
  "hooks-extra-ensure-use-memo-has-non-empty-deps": "hooks-extra/ensure-use-memo-has-non-empty-deps",
  "hooks-extra-prefer-use-state-lazy-initialization": "hooks-extra/prefer-use-state-lazy-initialization",
  "naming-convention-component-name": "naming-convention/component-name",
  "naming-convention-filename": "naming-convention/filename",
  "naming-convention-filename-extension": "naming-convention/filename-extension",
  "naming-convention-use-state": "naming-convention/use-state",
  "debug-class-component": "debug/class-component",
  "debug-function-component": "debug/function-component",
  "debug-react-hooks": "debug/react-hooks",
};
