export const projects = [
  { owner: "Ajaxy", repo: "telegram-tt" },
  { owner: "apache", repo: "hadoop" },
  { owner: "clientIO", repo: "joint" },
  { owner: "DimensionDev", repo: "Maskbook" },
  { owner: "electric-sql", repo: "electric" },
  { owner: "electric-sql", repo: "pglite" },
  { owner: "ensdomains", repo: "thorin" },
  { owner: "flirtual", repo: "flirtual" },
  { owner: "hashintel", repo: "hash" },
  { owner: "kriasoft", repo: "graphql-starter-kit" },
  { owner: "kriasoft", repo: "react-starter-kit" },
  { owner: "letstri", repo: "permix" },
  { owner: "Nexus-Mods", repo: "Vortex" },
  { owner: "npmgraph", repo: "npmgraph" },
  { owner: "offlegacy", repo: "event-tracker" },
  { owner: "onejs", repo: "one" },
  { owner: "payloadcms", repo: "payload" },
  { owner: "prettier", repo: "prettier" },
  { owner: "primer", repo: "react" },
  { owner: "prosekit", repo: "prosekit" },
  { owner: "react-navigation", repo: "react-navigation" },
  { owner: "refined-github", repo: "refined-github" },
  { owner: "TanStack", repo: "form" },
  { owner: "TanStack", repo: "pacer" },
  { owner: "TanStack", repo: "query" },
  { owner: "TanStack", repo: "router" },
  { owner: "TanStack", repo: "store" },
  { owner: "tisoap", repo: "react-flow-smart-edge" },
  { owner: "toss", repo: "suspensive" },
  { owner: "XYOracleNetwork", repo: "sdk-xyo-react-js" },
  { owner: "yjs", repo: "yjs-inspector" },
];

export const presets = [
  { owner: "AndreaPontrandolfo", repo: "sheriff" },
  { owner: "antfu", repo: "eslint-config" },
  { owner: "RebeccaStevens", repo: "eslint-config-rebeccastevens" },
  { owner: "SukkaW", repo: "eslint-config-sukka" },
  { owner: "upleveled", repo: "eslint-config-upleveled" },
];
