#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

pnpm run format:write
pnpm run lint
pnpm run build
cd packages/eslint-plugin
pnpm run build:docs-rules
pnpm publint
cd ../..
pnpm run format:write
git add .
