name: Check
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches:
      - "**"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
env:
  NODE_OPTIONS: --max_old_space_size=10240
permissions:
  contents: read
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Setup node@26
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 26
          package-manager-cache: false
      - name: Setup nub
        uses: nubjs/setup-nub@47e5e7393d50f4e9544ddaf756aa277972afba2d # v0.4.0
      - name: Install dependencies
        run: nub install --frozen-lockfile
      - name: Check formatting
        run: nub run format:check
      - name: Build packages
        run: nub run build
      - name: Lint
        run: nub run lint
      - name: Verify rules
        run: nub run check:rules
      - name: Lint MDX
        run: nub run lint:mdx
      - name: Check website types
        run: nub run --filter "./apps/website" types:check
      - name: Verify generated files are up to date
        run: git --no-pager diff --exit-code
