name: Check Provenance
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches:
      - main
permissions:
  contents: read
jobs:
  check-provenance:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 2
          sparse-checkout: |
            /*
            !.repos/
          sparse-checkout-cone-mode: false
      - name: Check provenance downgrades
        uses: danielroe/provenance-action@41bcc969e579d9e29af08ba44fcbfdf95cee6e6c # v0.1.1
        id: check
        with:
          fail-on-provenance-change: true # optional, default: false
          lockfile: pnpm-lock.yaml # optional
          #   base-ref: origin/main         # optional, default: origin/main
          fail-on-downgrade: true # optional, default: true
