name: Check
on:
  push:
    branches:
      - "**"
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches:
      - "**"
env:
  NODE_OPTIONS: --max_old_space_size=10240
permissions:
  contents: read
jobs:
  check:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Setup node@24
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.0.0
        with:
          node-version: 24
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v5.0.0
      - name: Install front-end dependencies
        run: pnpm install
      - name: Build front-end assets
        run: pnpm run build
      - name: Check
        run: pnpm run lint
      - name: Verify rules docs
        run: pnpm run verify:rule-docs
