name: Publish
on:
  push:
    branches:
      - main
jobs:
  check:
    name: Check
    permissions:
      contents: read
    uses: ./.github/workflows/check.yml
  test:
    name: Test
    permissions:
      contents: read
    uses: ./.github/workflows/test.yml
  zizmor:
    name: GitHub Actions Security Analysis
    permissions:
      contents: read
    uses: ./.github/workflows/zizmor.yml
  publish:
    name: Publish
    if: "${{ startsWith(github.event.head_commit.message, 'release: ') }}"
    needs: [check, test, zizmor]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Setup pnpm and node@24
        uses: pnpm/setup@5d160c5bc68a09337ad0d5654e237e03253b5879 # v1
        with:
          runtime: node@24
          install: false
      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts
      - name: Build packages
        run: node --run build
      - name: Publish
        run: |
          if git log -1 --pretty=%B | grep "^release: [0-9]\+\.[0-9]\+\.[0-9]\+$";
          then
            pnpm --filter "./packages/*" --filter "./plugins/*" publish --provenance --access public
          elif git log -1 --pretty=%B | grep "^release: [0-9]\+\.[0-9]\+\.[0-9]\+-rc\.[0-9]\+$";
          then
            pnpm --filter "./packages/*" --filter "./plugins/*" publish --provenance --access public --tag rc --no-git-checks
          elif git log -1 --pretty=%B | grep "^release: [0-9]\+\.[0-9]\+\.[0-9]\+-beta\.[0-9]\+$";
          then
            pnpm --filter "./packages/*" --filter "./plugins/*" publish --provenance --access public --tag beta --no-git-checks
          elif git log -1 --pretty=%B | grep "^release: [0-9]\+\.[0-9]\+\.[0-9]\+-next\.[0-9]\+$";
          then
            pnpm --filter "./packages/*" --filter "./plugins/*" publish --provenance --access public --tag next --no-git-checks
          else
            echo "Not a release, skipping publish"
          fi
