name: Test
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches:
      - "**"
env:
  NODE_OPTIONS: --max_old_space_size=102400
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Setup node@24
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.0.0
        with:
          node-version: 24
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v5.0.0
      - name: Install front-end dependencies
        run: pnpm install
      - name: Build front-end assets
        run: pnpm run build
      - name: Test on node@22
        run: pnpm run test
      - name: Setup node@22
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.0.0
        with:
          node-version: 22
      - name: Test on node@22
        run: pnpm run test
