name: Test
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches:
      - "**"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
env:
  NODE_OPTIONS: --max_old_space_size=10240
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Setup pnpm and node@24
        uses: pnpm/setup@5d160c5bc68a09337ad0d5654e237e03253b5879 # v1
        with:
          runtime: node@24
          install: false
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build packages
        run: pnpm run build
      - name: Test on node@24
        run: pnpm run test
      - name: Setup node@22
        uses: pnpm/setup@5d160c5bc68a09337ad0d5654e237e03253b5879 # v1
        with:
          runtime: node@22
          install: false
      - name: Test on node@22
        run: pnpm run test
